version: "3.9"

services:
  frontend:
    build:
      context: ./devhub-frontend
    ports:
      - "5173:5173" # Vite dev server
    volumes:
      - ./devhub-frontend:/app
#      - /app/node_modules
    command: npm run dev
    environment:
      - VITE_API_NEST=http://localhost:3000
    depends_on:
      - backend

  backend:
    build:
      context: ./devhub-backend
    ports:
      - "3000:3000"
    volumes:
      - ./devhub-backend:/app
#      - /app/node_modules
    command: npm run start:dev
    environment:
      - NODE_ENV=development
